# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20180117_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('tweet', models.ManyToManyField(to='tweets.Tweet')),
            ],
        ),
    ]
